# -*- coding: utf-8 -*-
"""example.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTxhJgNQHsVP0tEEsewG_EDqDXnuIkFq
"""

import pandas as pd

df = pd.read_csv('housing_data.csv')

df.head()

df.describe()

df.info()

df.isna().sum()

df.dtypes

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

list1=['Area (sqft)','Age','Price (in $1000s)']

df[list1] = scaler.fit_transform(df[list1])

df.head()

import matplotlib.pyplot as plt # Ensures matplotlib.pyplot is imported and available as plt
import seaborn as sns

core = df.corr()

plt.figure(figsize=(10,10))
sns.heatmap(core,annot=True,cmap='Blues')
plt.show()

df.hist(figsize=(10,10),bins=10)
plt.show()

X = df[["Rooms", "Area (sqft)", "Age"]]
y = df["Price (in $1000s)"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)

from sklearn.metrics import mean_squared_error

lr_accuracy = mean_squared_error(y_test,y_pred)

lr_accuracy

results = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})

results

import joblib
joblib.dump(lr, "price_predictor_model.pkl")

